@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [HaustierController]
  [HaustierResolver]

  [HaustierService]

  [Repository<Haustier>]

  [MailService]
}


cloud {
    [TypeORM]
}

cloud {
    [nest-keycloak-connect]
}

cloud {
    [nodemailer]
}

database "DB haustier" {
    [Tabelle haustier]
    [Tabelle beschreibung]
    [Tabelle foto]
    [Tabelle haustierFile]
}

node {
    [Keycloak]
}

node {
    [Mailserver]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [HaustierController]
[RequestLoggerMiddleware] ~~> [HaustierResolver]

[HaustierController] ..> [HaustierService]
[HaustierResolver] ..> [HaustierService]
[HaustierService] ..> [Repository<Haustier>]

[Repository<Haustier>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle haustier]
[TypeORM] ~~> [Tabelle beschreibung]
[TypeORM] ~~> [Tabelle foto]
[TypeORM] ~~> [Tabelle haustierFile]

[HaustierController] ..> [nest-keycloak-connect]
[HaustierResolver] ..> [nest-keycloak-connect]
[nest-keycloak-connect] ~~> [Keycloak]

[HaustierService] ..> [MailService]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

[MailService] ~[hidden]~> [nest-keycloak-connect]

footer (c) Alisa Ganter

@enduml
