@startuml Sequenzdiagramm

actor Haustier

boundary HaustierGetController
control HaustierReadService
database haustier

Haustier -> HaustierGetController : GET / getById()
HaustierGetController -> HaustierReadService: findById()
HaustierReadService -> haustier: [TypeORM]

footer (c) Alisa Ganter

@enduml
