@startuml Use Cases

actor Gast
actor Admin
actor Kunde

rectangle haustier {
    Gast --> (Haustier suchen)
    Admin --> (Haustier suchen)
    Admin --> (Haustier anlegen)
    Admin --> (Haustier ändern)
    Admin --> (Haustier löschen)
    Kunde --> (Haustier suchen)
    Kunde --> (Haustier anlegen)
    Kunde --> (Haustier ändern)
}

footer (c) Alisa Ganter

@enduml
